base_image: "anyscale/ray-ml:nightly-py37-gpu"

debian_packages:
  - curl

python:
  pip_packages:
    - ray-lightning
    - tblib
  conda_packages: []

post_build_cmds:
  - pip uninstall -y ray || true
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
  - echo {{ env["TIMESTAMP"] }} # Trigger re-build of cluster env so we get most up to date ray lightning version.
